name: Train Model

on:
  push:
    branches:
      - main  # Jalankan workflow ini setiap kali ada perubahan di branch main
  pull_request:
    branches:
      - main  # Jalankan workflow ini setiap kali ada pull request ke branch main

jobs:
  train_model:
    runs-on: ubuntu-latest  # Menggunakan runner Ubuntu terbaru di GitHub Actions

    steps:
      # 1. Checkout kode dari repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Menyiapkan Python versi 3.8

      # 3. Install dependencies dari requirements.txt
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Login ke WandB menggunakan API key dari Secrets
      - name: Login to WandB
        run: |
          echo "WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}" > ~/.netrc  # Login otomatis ke WandB

      # 5. Jalankan script pelatihan model
      - name: Run Training Script
        run: |
          python train.py  # Jalankan script pelatihan model di sini

      # 6. Upload model yang telah dilatih sebagai GitHub Artifact
      - name: Upload Trained Model Artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: trained_model.pth  # Pastikan nama file model sama dengan yang disimpan di train.py
