name: Automate Model Development

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train_model:
    runs-on: ubuntu-latest  # Gunakan runner Ubuntu terbaru

    steps:
    # Checkout kode dari repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # Install dependencies dari requirements.txt
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Buat folder models/resnet18 jika belum ada
    - name: Create model directory
      run: mkdir -p models/resnet18

    # Login ke WandB dengan API Key
    - name: WandB Login
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      run: |
        wandb login $WANDB_API_KEY  # Menggunakan API key dari secret GitHub

    # Run training script (asumsi script pelatihan Anda bernama Train.py)
    - name: Run Training
      run: |
        python Train.py  # Jalankan script pelatihan model di sini

    # Simpan model terlatih sebagai artifact GitHub
    - name: Upload Model Artifact
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: models/resnet18/  # Path folder model yang telah dibuat
