name: Train Model

on:
  push:
    branches:
      - main  # Jalankan workflow ini setiap kali ada perubahan di branch main
  pull_request:
    branches:
      - main  # Jalankan workflow ini setiap kali ada pull request ke branch main

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set WANDB API Key
      run: |
        echo "WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}" >> $GITHUB_ENV

    - name: Run Training
      run: |
        python Train.py  # Jalankan script pelatihan model Anda di sini

    - name: Upload Model Artifact
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: model/  # Sesuaikan dengan path direktori model Anda
